### PR TITLE
Updated to latest BB version

### PR DESCRIPTION
**Pull request by jampez77**

### CODE REVIEW

**Comment by chpego** [comment]
Thanks !

**Comment by OttPeterR** [comment]
Thanks for this! I'll test it later tonight and merge it in

**Comment by OttPeterR** [comment]
testing it now and running into the suexe error so work on that in parallel and I'll have it out some time this weekend (but no promises)

**Comment by OttPeterR** [comment]
turns out that a lot needed to change to get the suexe error fixed, so I threw in the version bump to that release as well, so I'll close out of this PR, but thanks for making sure it stays updated!

**Pull request closed without merging**
