### PR TITLE
Fix migrations, implement homeassistant-setting for babybuddy

### PR DESCRIPTION
**Pull request by MrApplejuice**
(Depends on a as of today uncommitted Babybuddy feature... which is why this is a draft atm)

Issue https://github.com/OttPeterR/addon-babybuddy/issues/47

Changes:
- Select special homeassistant configuration of babybuddy to run
- Update dependencies so that builds succeed
- Switched around migration and createcachetable commands to fix migration step of installing the addon

### CODE REVIEW

**Comment by OttPeterR** [comment]
Thanks for teeing this up 👍 if there’s any changes in the meantime I might need you to merge from main but I’ll let you know!

**Comment by MrApplejuice** [comment]
Hey! No worries, testing it all was the costly bit that required all things to fall in place and be tested and verified. Updating from `main` should not be the issue. But let's wait first until this PR is merged:

https://github.com/babybuddy/babybuddy/pull/672

That one is the prerequisite for this to be merged.

**Comment by MrApplejuice** [comment]
[Release 2.0](https://github.com/babybuddy/babybuddy/releases/tag/v2.0.0) was published! Time to get this "fixed" :-)

**Comment by MrApplejuice** [comment]
Alright. This should do the trick. Local testing tells me that this should build right now...

**Comment by reid** [comment]
Hey @MrApplejuice, I just wanted to leave a note here to thank you for this contribution and the work you have done in Baby Buddy to make this work.

This fix addresses my wife's top complaint with using Baby Buddy via Ingress when toasts cannot be dismissed!

I am very thankful for @OttPeterR also for maintaining this addon! I am a new dad and this tool has been so useful for my family. We are eagerly anticipating getting to use this fix but understand we are all busy being parents too 😃 thanks for all you are doing!

**Comment by MrApplejuice** [comment]
Hey @reid  - glad this helps with some other issues, too!

And thank you for the kind words!

**Comment by OttPeterR** [comment]
I'm pulling in your changes into my v2.0.x branch and that'll ship when I finish my testing of the new stuff. Thanks again for the PR, I really appreciate it!

**Pull request merged**
